# Generated by Django 6.1.1 on 2026-09-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_savedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ban_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
